name: publish-to-medium

on:
  workflow_dispatch:
    inputs:
      markdown_file:
        description: 'Path to the markdown file to publish'
        required: true
        default: './_posts/'
  push:
    paths:
      - '_posts/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.6.0
        with:
          integration_token: "${{ secrets.MEDIUM_INTEGRATION_TOKEN }}"
          file: ${{ inputs.markdown_file }}
          content_format: "markdown"
          notify_followers: "false"
          tags: "test,tag"
          title: "title"
          license: "all-rights-reserved"
          publish_status: "draft"
  
