name: publish-file-to-medium

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to publish'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read file content
      id: read_file
      run: |
        content=$(cat ${{ github.event.inputs.file_path }})
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"        
        echo "::set-output name=content::$content"   
        echo "$content"
        
    - name: Deploy to Medium
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://medium.azurewebsites.net/api/Publisher'
        method: 'POST'
        customHeaders: '{"Content-Type": "text/markdown"}'
        data: |
          {
            "content": $content
          }
