name: publish-to-medium
on:
  workflow_dispatch:
    inputs:
      markdown_file:
        description: 'Path to the markdown file to publish'
        required: true
        default: './_posts/post.md'
  push:
    paths:
      - '_posts/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish to Medium
        uses: infraway/medium-post-markdown@v1.6.0
        with:
          access_token: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
          markdown_file: ${{ github.event.inputs.markdown_file }}
